version: "3"
services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_gateway
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
